### ISSUE TITLE
get related foreign key targets name and not attname

### ISSUE THREAD

**Issue by menelike** [simone/django-compositekey#21] opened 2013-04-30 13:22 UTC
Hi,

when we have the following models:

<pre>
class BAR(models.Model):
    bar = models.DecimalField(primary_key=True, max_digits=3, decimal_places=0, blank=False, null=False, )

class FOO(models.Model):
    id = db.MultiFieldPK("foo", "bar")
    foo = models.DecimalField(max_digits=9, decimal_places=0, blank=False, null=False, )
    bar = models.ForeignKey(BAR)
</pre>

the related name on db.models.fields.wrap Line 25 

<pre>
setattr(obj, cache_name, assemble_pk(*[f.get_prep_value(getattr(obj, f.name)) for f in fields]))
</pre>

looks for the fieldname, not for the attname like in

<pre>
setattr(obj, cache_name, assemble_pk(*[f.get_prep_value(getattr(obj, f.attname)) for f in fields]))
</pre>

which doesn't find the related object and raises a DoesNotExist.

I'm not sure if choosing the field instead of the attname has some purpose. Furthermore this could break dependencies.

Tested with 1.4.x Branch on Django 1.4.3.

Cheers

**Comment by simone** [comment] 2013-05-02 07:13
Hi,

thanks for the feedback,
It is fixed now.

duplicate of #16

**Closed as completed by simone** 2013-05-02 07:13 UTC
